### ISSUE TITLE
Alternative to MTOM

### ISSUE THREAD

**Issue by AndreasLudviksen** [ks-no/ks-no.github.io#12]
We are using 'ForesendelsesServiceV9' and we are migrating to .NET Core.
Your documentation states to use MTOM, which has limited support on .NET Core.

Is it possible for us to use a different message encoding against your service?

**Comment by zapodot** [comment]
Hi! Your best option would be to use our ReST service which is documented at https://ks-no.github.io/svarut/integrasjon/forsendelserestservicev1/
