### ISSUE TITLE
Konsekvent navngivning av datafelt

### ISSUE THREAD

**Issue by maccyber** [ks-no/ks-no.github.io#2]
Ønsker at data felt blir benyttet konsekvent - i eksempel:

For **retrieveSigneringshistorikk** må man sende med feltet `forsendelseid`
For **retrieveForsendelseStatus** og **retrieveForsendelseHistorikk** må man sende med feltet `forsendelsesid` (med s)

**Comment by bnese** [comment]
Takk for tilbakemelding.
Korrekt skrivemåte er forsendelsesid, altså med s. Dette vil bli korrigert i versjon V10 av ForsendelseService.
