### ISSUE TITLE
Ikke benytt fødselsnummer i Azure AD attributter 

### ISSUE THREAD

**Issue by JMyklebust** [ks-no/ks-no.github.io#32]
Ref. https://ks-no.github.io/fiks-plattform/sentralisertbrukerstyring/

Ikke benytt attributt felter i Azure AD til å overføre fødselsnummer.
Disse attributt feltene er på ingen måte "hemmelige".

En hvilken som helst bruker kan gjøre dette:
```powershell
# https://docs.microsoft.com/en-us/powershell/azure/active-directory/install-adv2?view=azureadps-2.0
Install-Module AzureAD
Connect-AzureAD # Bruk en upriviligert/vanlig brukerkonto her
$Users = Get-AzureADUser -All
# Hvis attributtet heter 'foedselsnumer'
$Users.ExtensionProperty.foedselsnummer
```

Og vipps så har denne uprvilgerte brukerene høste alle fødselsnummrene som finnes i Azure AD

**Comment by idar** [comment]
Dette er diskutert og vi ser problemet. Det er ingen andre løsninger på dette nå på dette tidspunktet.

**Comment by zapodot** [comment]
Microsoft har laget noe de kaller custom secure attributes som man kan bruke til attributter man vil skjule, ref. https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/custom-security-attributes-overview

**Comment by JMyklebust** [comment]
Den funksjonen er pt. i Preview og dekkes ikke av ordinære bruksvilkår.
Det er egene vilkår for bruk av Preview funksjoner.
https://azure.microsoft.com/en-us/support/legal/preview-supplemental-terms/

> Pursuant to the terms of your Azure subscription, PREVIEWS ARE PROVIDED "AS-IS," "WITH ALL FAULTS," AND "AS AVAILABLE," AND ARE EXCLUDED FROM THE SERVICE LEVEL AGREEMENTS AND LIMITED WARRANTY. Previews may not be covered by customer support. Previews may be subject to reduced or different security, compliance and privacy commitments, as further explained in the Microsoft Privacy Statement, Microsoft Azure Trust Center, the Product Terms, the DPA, and any additional notices provided with the Preview. The following terms in the DPA do not apply to Previews: Processing of Personal Data; GDPR, Data Security, and HIPAA Business Associate. Customers should not use Previews to process Personal Data or other data that is subject to heightened legal or regulatory requirements.

Denne biten her på slutten er veldig viktig i sammenheng med personvern:
 **_The following terms in the DPA do not apply to Previews: Processing of Personal Data; GDPR, Data Security, and HIPAA Business Associate. Customers should not use Previews to process Personal Data or other data that is subject to heightened legal or regulatory requirements._**



I tillegg så kommer det som skjer rundt Schrems II dommen på toppen her så man burde i aller høyeste grad ha alternativer som ikke er avhengig av Azure AD eller andre autentiseringsløsninger i sky (med mindre leverandør er europeisk og kan i større grad garanteres at overholder GDPR) .
